sudo: required

language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: awt-05
    token: "${SONAR_TOKEN}"

script:
  - ./gradlew check
  - sonar-scanner
  - ./gradlew executeBDDTests -PapiKey=$API_KEY -PapiToken=$API_TOKEN -PfilterTags=@functional

notifications:
  email: true
